stages:
  - static-analysis
  - build
  - test
  - deploy

.push-container:
  stage: build
  variables: 
    IMAGE_NAME: $CI_PROJECT_NAME
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
    DOCKERFILE: Dockerfile
    ASSETS_DIRECTORY: assets
    REGISTRY: $CI_REGISTRY
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    DESTINATIONS: "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG"
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  rules:
    - changes:
      - $DOCKERFILE
      - $ASSETS_DIRECTORY
  script:
    - echo "{\"auths\":{\"${REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${REGISTRY_USER}" "${REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${DOCKERFILE}"
      --destination "${DESTINATIONS}"
